import type { AggregatedNews } from '../aggregator.js';
import type { NewsItem } from '../sources/rss.js';

function formatDate(date: Date): string {
  return date.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function formatTime(date: Date): string {
  return date.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  });
}

function getPointsColor(points: number): string {
  if (points >= 25) return '🔥';
  if (points >= 20) return '⭐';
  if (points >= 15) return '✨';
  if (points >= 10) return '👍';
  return '📌';
}

function renderNewsItem(item: NewsItem): string {
  const lines: string[] = [];
  const pointsIcon = getPointsColor(item.points);
  lines.push(`- **[${item.title}](${item.url})** ${pointsIcon} \`${item.points} pts\``);
  lines.push(`  - Source: ${item.source} | ${formatTime(item.publishedAt)}`);
  if (item.summary) {
    lines.push(`  - ${item.summary}`);
  }
  return lines.join('\n');
}

const CATEGORY_EMOJI: Record<string, string> = {
  world: '🌍',
  finance: '💹',
  tech: '💻',
  vc: '💰',
};

function renderCategory(category: string, items: NewsItem[]): string {
  const emoji = CATEGORY_EMOJI[category.toLowerCase()] || '📰';
  const capitalizedCategory = category.charAt(0).toUpperCase() + category.slice(1);
  const totalPoints = items.reduce((sum, item) => sum + item.points, 0);
  const lines: string[] = [];
  
  lines.push(`## ${emoji} ${capitalizedCategory} News (${totalPoints} total points)`);
  lines.push('');
  items.forEach((item) => {
    lines.push(renderNewsItem(item));
    lines.push('');
  });
  return lines.join('\n');
}

export function generateMarkdown(news: AggregatedNews): string {
  const lines: string[] = [];
  const totalPoints = news.items.reduce((sum, item) => sum + item.points, 0);

  lines.push(`# Daily News Digest`);
  lines.push('');
  lines.push(`**Generated:** ${formatDate(news.generatedAt)} at ${formatTime(news.generatedAt)}`);
  lines.push('');
  lines.push(`**Total Articles:** ${news.totalCount}`);
  lines.push(`**Total Points:** ${totalPoints} 🎯`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('### Points Legend');
  lines.push('- 🔥 25+ points: Trending & High Quality');
  lines.push('- ⭐ 20-24 points: Excellent Quality');
  lines.push('- ✨ 15-19 points: Very Good');
  lines.push('- 👍 10-14 points: Good Quality');
  lines.push('- 📌 <10 points: Standard');
  lines.push('');
  lines.push('---');
  lines.push('');

  // Order categories: world, finance, tech
  const categoryOrder = ['world', 'finance', 'tech', 'vc'];
  const categories = Object.keys(news.byCategory).sort((a, b) => {
    const aIndex = categoryOrder.indexOf(a.toLowerCase());
    const bIndex = categoryOrder.indexOf(b.toLowerCase());
    if (aIndex === -1 && bIndex === -1) return a.localeCompare(b);
    if (aIndex === -1) return 1;
    if (bIndex === -1) return -1;
    return aIndex - bIndex;
  });

  for (const category of categories) {
    lines.push(renderCategory(category, news.byCategory[category]));
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by [News Aggregator](https://github.com)*');

  return lines.join('\n');
}
